#!/bin/bash
# Assigment 1 : System Report
# Student = Sebastian Patino
# Studnet NUmber = 200528397
 
# variables that I can call later
username=$(whoami)
hostname=$(hostname)
date_time=$(date)
uptime=$(uptime -p)
cpu=$(lscpu | grep 'Model name:'| awk -F ":" '{print $2}')
Cpu_speed=$(grep 'cpu MHz' /proc/cpuinfo | awk '{print $4}' | head -1)
CpuMaxSpeed=
OSinfo=$(cat /etc/os-release | grep PRETTY_NAME= | awk -F '"' '{print $2}')
RamInfo=$(free -h | awk '/^Mem:/ {print $2}')
DiskMake=$(udevadm info --query=all --name=/dev/sda | awk -F "=" '/ID_MODEL=|ID_VENDOR=/{print $2}')
DiskSize=$(df -h / | awk 'NR==2 {print $2}' )
DiskName=$(ls -l /dev/disk/by-id/ |awk '{print $9}')
GPUinfo=$(lspci -v | grep -A1 -i vga |awk -F 'Subsystem:' '{print $2}' )
GatewayIp=$(ip r | awk 'NR==1 {print $3}')
HostIp=$( ip r | awk 'NR==3 {print $9}')
DNS=$(grep -i nameserver /etc/resolv.conf |awk '{print $2}')
InterfaceName=$(ip -4 route show default | awk '/dev/ {print $5}')
InterfaceIp=$(ip -4 addr show "$InterfaceName" | awk '/inet / {print $2}')
UsersLoging=$(who | awk '{print $1}' | paste -s -d ',' -)
DiskSpace=$(df -h | awk '!/tmpfs/ {print $1, $4}')
FQDN=$(hostname  --fqdn)
LoadAv=$(cat /proc/loadavg | awk '{print $1",", $2",", $3}')
MemoryAllocation=$(free -m | awk 'NR==2 {print $4}')
ListeningPorts=$(ss -tuln | awk 'NR > 1 {print $5}' | cut -d':' -f2 | sort -n | uniq|paste -s -d ',' - )
ufwEnable=$(sudo ufw status|awk '{print $2}')
Process=$(ps -e --no-headers | wc -l )

cat << E0F
--------------------------------------------

System Report Generated by : $username
Time of the Report :  $date_time

-----------------------------
System Information
-------------------
Hostname: $hostname
OS: $OSinfo
Uptime: $uptime
----------------------
Hardware Information
----------------------
cpu:$cpu
Max CPU Speed: $Cpu_speed
Ram: $RamInfo

---------------------
Disk Information
-----------------------
Make and model: $DiskMake

Disk Size:$DiskSize

------------------------
Video GPU Info
-------------------------
$GPUinfo

-----------------------
Network Information
---------------------
FQDN: $FQDN
Host Address: $HostIp
Gateway IP: $GatewayIp
DNS Server: $DNS


InterfaceName:
$InterfaceName
IP Address:
$InterfaceIp


--------------
System Status
--------------
Users Logged In:  $UsersLoging

Disk Space: $DiskSpace

Process Count: $Process
Load Averages: $LoadAv
Memory Allocation: $MemoryAllocation
Listening Network Ports: $ListeningPorts
UFW Rules: $ufwEnable
